---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1kvlyxmyq26d7ux9lvwxmtncraheh86ne7pars2zslud66yxdsu0q35z48k"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1kvlyxmyq26d7ux9lvwxmtncraheh86ne7pars2zslud66yxdsu0q35z48k"
stores:
  yaml:
    indent: 2
