apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:pA2mpsqX9Cqpe2x7imNjQbnVTg==,iv:kGypu2dLwS1R6V3mcJAXT0rg7/ckPDXYRaTsbvnKYzY=,tag:JjGZqtCVK8h35a4CQsD/2A==,type:str]
sops:
  age:
    - recipient: age1kvlyxmyq26d7ux9lvwxmtncraheh86ne7pars2zslud66yxdsu0q35z48k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTFplNituTklRZkxkNFl6
        allDcnBNNFRwbVJBaENVTE1mekd4bmFPNEVrCjhYckdWRm9ub1Zaa0FSTjNLdEtP
        ZWRJd2UyNm5XT2tWME5GQWZqRXVmejQKLS0tIDFGUmxXczFpQjhBd1FoK2dlandw
        UDdGcjlnOTc0SkNGSklqTk4zdkd3NXMKeLB/3GUXPOIoyf6EUCrod8TPQaf5QmzB
        jC0Z4K4D9mOy4SahA652sSlzjjdkmQ+usuUriGmi0qbEiRAXjOxwvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-05T06:13:24Z"
  mac: ENC[AES256_GCM,data:wXUnKOUltxD+O+9sGXmPktorELV8XiJQ3UZvOVErLsHxCiF2GmK3Tjyn+WjlxM6Pu29XrD/sO6d9vKI1kF3rs+Lm+Guor6+RcvPltkI/OnXi86DMc33Fis1DfUbq50LdX80j+8c/Irio4c3fxg38Fy8KOhioCkTKxLKWe4w2XXQ=,iv:c/1rMKak0XDUdn7axOU28iIsdBpOpYgw8SvRewB762M=,tag:z5VUc+0+nMfxc85l21HcVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
